version: "3.7"
services:
  app:
    build:
      args:
        user: alysson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: commuback
    container_name: commuback-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7
    container_name: commuback-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "commuback_db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1

  nginx:
    image: nginx:alpine
    container_name: commuback-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/